CREATE TABLE IF NOT EXISTS pianos (
	id TEXT NOT NULL PRIMARY KEY
  model TEXT NOT NULL
  created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE IF NOT EXISTS images (
	id TEXT NOT NULL PRIMARY KEY
  url TEXT NOT NULL
  piano_id TEXT NOT NULL
  FOREIGN KEY (piano_id) REFERENCES pianos(id)
);
